credentials:
  usernames:
    freddy:
      email: freddypinto@gmail.com
      name: Freddy
      password: $2b$12$W26vrUbMJDjuv5A1UK5uaO/UwSGlApTs/h0anlAV2W/8LEEHg4NGu
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca
      password: $2b$12$ILkTZlgjTKq2bpOKz9MoT./xKp3i.yszLzw81Z0/IO8S7hqf8hvdK
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - admin@gmail.com